version: '2.4'
services:
    obu1:
        hostname: obu
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=0
            - VANETZA_STATION_TYPE=7
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:
            kernel.msgmax: 16384

    obu2:
        hostname: obu
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=7
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
        sysctls:
            kernel.msgmax: 16384

networks:
    vanetzalan0:
        external: true
        name: vanetzalan0
