# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.17)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Vanetza::access Vanetza::asn1_support Vanetza::asn1_its Vanetza::asn1_security Vanetza::asn1_pki Vanetza::asn1 Vanetza::btp Vanetza::common Vanetza::dcc Vanetza::facilities Vanetza::geonet Vanetza::gnss Vanetza::net Vanetza::security Vanetza::socktap Vanetza::vanetza)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Vanetza::access
add_library(Vanetza::access STATIC IMPORTED)

set_target_properties(Vanetza::access PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::net"
)

# Create imported target Vanetza::asn1_support
add_library(Vanetza::asn1_support STATIC IMPORTED)

set_target_properties(Vanetza::asn1_support PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza;/home/rrosmaninho/Repos/IT/vanetza/vanetza/asn1/support"
)

# Create imported target Vanetza::asn1_its
add_library(Vanetza::asn1_its STATIC IMPORTED)

set_target_properties(Vanetza::asn1_its PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1_security
add_library(Vanetza::asn1_security STATIC IMPORTED)

set_target_properties(Vanetza::asn1_security PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1_pki
add_library(Vanetza::asn1_pki STATIC IMPORTED)

set_target_properties(Vanetza::asn1_pki PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_support"
)

# Create imported target Vanetza::asn1
add_library(Vanetza::asn1 STATIC IMPORTED)

set_target_properties(Vanetza::asn1 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::asn1_its;Boost::boost"
)

# Create imported target Vanetza::btp
add_library(Vanetza::btp STATIC IMPORTED)

set_target_properties(Vanetza::btp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Boost::boost;Vanetza::geonet"
)

# Create imported target Vanetza::common
add_library(Vanetza::common STATIC IMPORTED)

set_target_properties(Vanetza::common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Boost::date_time;Threads::Threads"
)

# Create imported target Vanetza::dcc
add_library(Vanetza::dcc STATIC IMPORTED)

set_target_properties(Vanetza::dcc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::access;Vanetza::net"
)

# Create imported target Vanetza::facilities
add_library(Vanetza::facilities STATIC IMPORTED)

set_target_properties(Vanetza::facilities PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Boost::date_time;Vanetza::asn1;Vanetza::security;\$<LINK_ONLY:Vanetza::geonet>"
)

# Create imported target Vanetza::geonet
add_library(Vanetza::geonet STATIC IMPORTED)

set_target_properties(Vanetza::geonet PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:GeographicLib::GeographicLib>;Boost::date_time;Vanetza::dcc;Vanetza::net;Vanetza::security"
)

# Create imported target Vanetza::gnss
add_library(Vanetza::gnss STATIC IMPORTED)

set_target_properties(Vanetza::gnss PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Boost::date_time"
)

# Create imported target Vanetza::net
add_library(Vanetza::net STATIC IMPORTED)

set_target_properties(Vanetza::net PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::common"
)

# Create imported target Vanetza::security
add_library(Vanetza::security STATIC IMPORTED)

set_target_properties(Vanetza::security PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "VANETZA_WITH_CRYPTOPP"
  INTERFACE_INCLUDE_DIRECTORIES "/home/rrosmaninho/Repos/IT/vanetza"
  INTERFACE_LINK_LIBRARIES "Vanetza::common;Vanetza::net;\$<LINK_ONLY:GeographicLib::GeographicLib>;CryptoPP::CryptoPP"
)

# Create imported target Vanetza::socktap
add_executable(Vanetza::socktap IMPORTED)

# Create imported target Vanetza::vanetza
add_library(Vanetza::vanetza INTERFACE IMPORTED)

set_target_properties(Vanetza::vanetza PROPERTIES
  INTERFACE_LINK_LIBRARIES "Vanetza::access;Vanetza::asn1_support;Vanetza::asn1_its;Vanetza::asn1_security;Vanetza::asn1_pki;Vanetza::asn1;Vanetza::btp;Vanetza::common;Vanetza::dcc;Vanetza::facilities;Vanetza::geonet;Vanetza::gnss;Vanetza::net;Vanetza::security"
)

# Import target "Vanetza::access" for configuration ""
set_property(TARGET Vanetza::access APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::access PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_access.a"
  )

# Import target "Vanetza::asn1_support" for configuration ""
set_property(TARGET Vanetza::asn1_support APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::asn1_support PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_asn1_support.a"
  )

# Import target "Vanetza::asn1_its" for configuration ""
set_property(TARGET Vanetza::asn1_its APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::asn1_its PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_asn1_its.a"
  )

# Import target "Vanetza::asn1_security" for configuration ""
set_property(TARGET Vanetza::asn1_security APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::asn1_security PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_asn1_security.a"
  )

# Import target "Vanetza::asn1_pki" for configuration ""
set_property(TARGET Vanetza::asn1_pki APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::asn1_pki PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_asn1_pki.a"
  )

# Import target "Vanetza::asn1" for configuration ""
set_property(TARGET Vanetza::asn1 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::asn1 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_asn1.a"
  )

# Import target "Vanetza::btp" for configuration ""
set_property(TARGET Vanetza::btp APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::btp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_btp.a"
  )

# Import target "Vanetza::common" for configuration ""
set_property(TARGET Vanetza::common APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::common PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_common.a"
  )

# Import target "Vanetza::dcc" for configuration ""
set_property(TARGET Vanetza::dcc APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::dcc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_dcc.a"
  )

# Import target "Vanetza::facilities" for configuration ""
set_property(TARGET Vanetza::facilities APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::facilities PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_facilities.a"
  )

# Import target "Vanetza::geonet" for configuration ""
set_property(TARGET Vanetza::geonet APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::geonet PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_geonet.a"
  )

# Import target "Vanetza::gnss" for configuration ""
set_property(TARGET Vanetza::gnss APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::gnss PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_gnss.a"
  )

# Import target "Vanetza::net" for configuration ""
set_property(TARGET Vanetza::net APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::net PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_net.a"
  )

# Import target "Vanetza::security" for configuration ""
set_property(TARGET Vanetza::security APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::security PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/lib/static/libvanetza_security.a"
  )

# Import target "Vanetza::socktap" for configuration ""
set_property(TARGET Vanetza::socktap APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(Vanetza::socktap PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/rrosmaninho/Repos/IT/vanetza/bin/socktap"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
